Progress JFXC-3561 : Compiled bind: Tests that do not compile.
Fixed bug 9: bind with inverse to a qualified name causes ClassCastException
 test/should-fail/jfxc1086.fx
     def c = bind jfxc1086.index with inverse;
        java.lang.ClassCastException: com.sun.tools.javafx.code.JavafxClassSymbol cannot be cast to com.sun.tools.mjavac.code.Symbol$VarSymbol
     - remove the jfxc1086 qualifier and the crash does not occur.

The test compiles now.

Testing: ran "ant dev-pass" on Mac OS X 10.5.8.