Progress JFXC-3561 : Compiled bind: Tests that do not compile.
Progress on bug 3: bind func in an anon class can't access outer class name
   test/regress/jfxc500.fx
    [junit] test/regress/jfxc500.fx:66: cannot find symbol
    [junit] symbol : variable jfxc500_3
    [junit] location: class jfxc500
    [junit] var n = bind jfxc500_3.name.toUpperCase(); // bind outer's name

Two problems fixed:

1) bug in lower with handling OuterClass.varName++
2) bug in translation - FunctionCallTranslator.isNamedSuperCall()

With these fixes, the above test compiles now. But, it fails at runtime (the
output does not match expected output) because of some other reason -
dependencies between local class bind expression and outer class field is not
properly handled (may need changes in decompose and translation).

Testing: ran "ant dev-pass" on Mac OS X 10.5.8.